// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myproject_axi,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.375000,HLS_SYN_LAT=289,HLS_SYN_TPT=290,HLS_SYN_MEM=2,HLS_SYN_DSP=2,HLS_SYN_FF=6544,HLS_SYN_LUT=15392,HLS_VERSION=2019_2}" *)

module myproject_axi (
        in_r_TDATA,
        in_r_TLAST,
        out_r_TDATA,
        out_r_TLAST,
        ap_clk,
        ap_rst_n,
        in_r_TVALID,
        in_r_TREADY,
        out_r_TVALID,
        out_r_TREADY
);


input  [31:0] in_r_TDATA;
input  [0:0] in_r_TLAST;
output  [31:0] out_r_TDATA;
output  [0:0] out_r_TLAST;
input   ap_clk;
input   ap_rst_n;
input   in_r_TVALID;
output   in_r_TREADY;
output   out_r_TVALID;
input   out_r_TREADY;

 reg    ap_rst_n_inv;
wire    Block_codeRepl1107_proc46_U0_ap_start;
wire    Block_codeRepl1107_proc46_U0_start_full_n;
wire    Block_codeRepl1107_proc46_U0_ap_done;
wire    Block_codeRepl1107_proc46_U0_ap_continue;
wire    Block_codeRepl1107_proc46_U0_ap_idle;
wire    Block_codeRepl1107_proc46_U0_ap_ready;
wire    Block_codeRepl1107_proc46_U0_start_out;
wire    Block_codeRepl1107_proc46_U0_start_write;
wire    Block_codeRepl1107_proc46_U0_in_r_TREADY;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_0_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_0_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_1_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_1_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_2_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_2_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_3_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_3_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_4_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_4_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_5_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_5_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_6_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_6_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_7_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_7_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_8_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_8_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_9_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_9_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_10_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_10_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_11_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_11_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_12_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_12_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_13_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_13_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_14_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_14_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_15_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_15_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_16_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_16_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_17_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_17_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_18_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_18_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_19_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_19_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_20_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_20_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_21_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_21_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_22_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_22_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_23_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_23_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_24_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_24_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_25_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_25_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_26_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_26_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_27_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_27_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_28_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_28_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_29_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_29_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_30_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_30_write;
wire   [31:0] Block_codeRepl1107_proc46_U0_in_local_V_data_V_31_din;
wire    Block_codeRepl1107_proc46_U0_in_local_V_data_V_31_write;
wire   [0:0] Block_codeRepl1107_proc46_U0_is_last_1_i_0_out_out_din;
wire    Block_codeRepl1107_proc46_U0_is_last_1_i_0_out_out_write;
wire    myproject_U0_input_1_V_data_0_V_read;
wire    myproject_U0_input_1_V_data_1_V_read;
wire    myproject_U0_input_1_V_data_2_V_read;
wire    myproject_U0_input_1_V_data_3_V_read;
wire    myproject_U0_input_1_V_data_4_V_read;
wire    myproject_U0_input_1_V_data_5_V_read;
wire    myproject_U0_input_1_V_data_6_V_read;
wire    myproject_U0_input_1_V_data_7_V_read;
wire    myproject_U0_input_1_V_data_8_V_read;
wire    myproject_U0_input_1_V_data_9_V_read;
wire    myproject_U0_input_1_V_data_10_V_read;
wire    myproject_U0_input_1_V_data_11_V_read;
wire    myproject_U0_input_1_V_data_12_V_read;
wire    myproject_U0_input_1_V_data_13_V_read;
wire    myproject_U0_input_1_V_data_14_V_read;
wire    myproject_U0_input_1_V_data_15_V_read;
wire    myproject_U0_input_1_V_data_16_V_read;
wire    myproject_U0_input_1_V_data_17_V_read;
wire    myproject_U0_input_1_V_data_18_V_read;
wire    myproject_U0_input_1_V_data_19_V_read;
wire    myproject_U0_input_1_V_data_20_V_read;
wire    myproject_U0_input_1_V_data_21_V_read;
wire    myproject_U0_input_1_V_data_22_V_read;
wire    myproject_U0_input_1_V_data_23_V_read;
wire    myproject_U0_input_1_V_data_24_V_read;
wire    myproject_U0_input_1_V_data_25_V_read;
wire    myproject_U0_input_1_V_data_26_V_read;
wire    myproject_U0_input_1_V_data_27_V_read;
wire    myproject_U0_input_1_V_data_28_V_read;
wire    myproject_U0_input_1_V_data_29_V_read;
wire    myproject_U0_input_1_V_data_30_V_read;
wire    myproject_U0_input_1_V_data_31_V_read;
wire   [31:0] myproject_U0_layer2_out_V_data_V_din;
wire    myproject_U0_layer2_out_V_data_V_write;
wire    myproject_U0_ap_start;
wire    myproject_U0_ap_done;
wire    myproject_U0_ap_ready;
wire    myproject_U0_ap_idle;
wire    myproject_U0_ap_continue;
wire    Block_myproject_axi_exit1109_proc_U0_ap_start;
wire    Block_myproject_axi_exit1109_proc_U0_ap_done;
wire    Block_myproject_axi_exit1109_proc_U0_ap_continue;
wire    Block_myproject_axi_exit1109_proc_U0_ap_idle;
wire    Block_myproject_axi_exit1109_proc_U0_ap_ready;
wire    Block_myproject_axi_exit1109_proc_U0_out_local_V_data_0_V_read;
wire   [31:0] Block_myproject_axi_exit1109_proc_U0_out_r_TDATA;
wire    Block_myproject_axi_exit1109_proc_U0_out_r_TVALID;
wire   [0:0] Block_myproject_axi_exit1109_proc_U0_out_r_TLAST;
wire    Block_myproject_axi_exit1109_proc_U0_is_last_1_i_0_loc_read;
wire    ap_sync_continue;
wire    in_local_V_data_V_0_full_n;
wire   [31:0] in_local_V_data_V_0_dout;
wire    in_local_V_data_V_0_empty_n;
wire    in_local_V_data_V_1_full_n;
wire   [31:0] in_local_V_data_V_1_dout;
wire    in_local_V_data_V_1_empty_n;
wire    in_local_V_data_V_2_full_n;
wire   [31:0] in_local_V_data_V_2_dout;
wire    in_local_V_data_V_2_empty_n;
wire    in_local_V_data_V_3_full_n;
wire   [31:0] in_local_V_data_V_3_dout;
wire    in_local_V_data_V_3_empty_n;
wire    in_local_V_data_V_4_full_n;
wire   [31:0] in_local_V_data_V_4_dout;
wire    in_local_V_data_V_4_empty_n;
wire    in_local_V_data_V_5_full_n;
wire   [31:0] in_local_V_data_V_5_dout;
wire    in_local_V_data_V_5_empty_n;
wire    in_local_V_data_V_6_full_n;
wire   [31:0] in_local_V_data_V_6_dout;
wire    in_local_V_data_V_6_empty_n;
wire    in_local_V_data_V_7_full_n;
wire   [31:0] in_local_V_data_V_7_dout;
wire    in_local_V_data_V_7_empty_n;
wire    in_local_V_data_V_8_full_n;
wire   [31:0] in_local_V_data_V_8_dout;
wire    in_local_V_data_V_8_empty_n;
wire    in_local_V_data_V_9_full_n;
wire   [31:0] in_local_V_data_V_9_dout;
wire    in_local_V_data_V_9_empty_n;
wire    in_local_V_data_V_10_full_n;
wire   [31:0] in_local_V_data_V_10_dout;
wire    in_local_V_data_V_10_empty_n;
wire    in_local_V_data_V_11_full_n;
wire   [31:0] in_local_V_data_V_11_dout;
wire    in_local_V_data_V_11_empty_n;
wire    in_local_V_data_V_12_full_n;
wire   [31:0] in_local_V_data_V_12_dout;
wire    in_local_V_data_V_12_empty_n;
wire    in_local_V_data_V_13_full_n;
wire   [31:0] in_local_V_data_V_13_dout;
wire    in_local_V_data_V_13_empty_n;
wire    in_local_V_data_V_14_full_n;
wire   [31:0] in_local_V_data_V_14_dout;
wire    in_local_V_data_V_14_empty_n;
wire    in_local_V_data_V_15_full_n;
wire   [31:0] in_local_V_data_V_15_dout;
wire    in_local_V_data_V_15_empty_n;
wire    in_local_V_data_V_16_full_n;
wire   [31:0] in_local_V_data_V_16_dout;
wire    in_local_V_data_V_16_empty_n;
wire    in_local_V_data_V_17_full_n;
wire   [31:0] in_local_V_data_V_17_dout;
wire    in_local_V_data_V_17_empty_n;
wire    in_local_V_data_V_18_full_n;
wire   [31:0] in_local_V_data_V_18_dout;
wire    in_local_V_data_V_18_empty_n;
wire    in_local_V_data_V_19_full_n;
wire   [31:0] in_local_V_data_V_19_dout;
wire    in_local_V_data_V_19_empty_n;
wire    in_local_V_data_V_20_full_n;
wire   [31:0] in_local_V_data_V_20_dout;
wire    in_local_V_data_V_20_empty_n;
wire    in_local_V_data_V_21_full_n;
wire   [31:0] in_local_V_data_V_21_dout;
wire    in_local_V_data_V_21_empty_n;
wire    in_local_V_data_V_22_full_n;
wire   [31:0] in_local_V_data_V_22_dout;
wire    in_local_V_data_V_22_empty_n;
wire    in_local_V_data_V_23_full_n;
wire   [31:0] in_local_V_data_V_23_dout;
wire    in_local_V_data_V_23_empty_n;
wire    in_local_V_data_V_24_full_n;
wire   [31:0] in_local_V_data_V_24_dout;
wire    in_local_V_data_V_24_empty_n;
wire    in_local_V_data_V_25_full_n;
wire   [31:0] in_local_V_data_V_25_dout;
wire    in_local_V_data_V_25_empty_n;
wire    in_local_V_data_V_26_full_n;
wire   [31:0] in_local_V_data_V_26_dout;
wire    in_local_V_data_V_26_empty_n;
wire    in_local_V_data_V_27_full_n;
wire   [31:0] in_local_V_data_V_27_dout;
wire    in_local_V_data_V_27_empty_n;
wire    in_local_V_data_V_28_full_n;
wire   [31:0] in_local_V_data_V_28_dout;
wire    in_local_V_data_V_28_empty_n;
wire    in_local_V_data_V_29_full_n;
wire   [31:0] in_local_V_data_V_29_dout;
wire    in_local_V_data_V_29_empty_n;
wire    in_local_V_data_V_30_full_n;
wire   [31:0] in_local_V_data_V_30_dout;
wire    in_local_V_data_V_30_empty_n;
wire    in_local_V_data_V_31_full_n;
wire   [31:0] in_local_V_data_V_31_dout;
wire    in_local_V_data_V_31_empty_n;
wire    is_last_1_i_0_loc_c_full_n;
wire   [0:0] is_last_1_i_0_loc_c_dout;
wire    is_last_1_i_0_loc_c_empty_n;
wire    out_local_V_data_0_V_full_n;
wire   [31:0] out_local_V_data_0_V_dout;
wire    out_local_V_data_0_V_empty_n;
wire   [0:0] start_for_myproject_U0_din;
wire    start_for_myproject_U0_full_n;
wire   [0:0] start_for_myproject_U0_dout;
wire    start_for_myproject_U0_empty_n;
wire   [0:0] start_for_Block_myproject_axi_exit1109_proc_U0_din;
wire    start_for_Block_myproject_axi_exit1109_proc_U0_full_n;
wire   [0:0] start_for_Block_myproject_axi_exit1109_proc_U0_dout;
wire    start_for_Block_myproject_axi_exit1109_proc_U0_empty_n;
wire    myproject_U0_start_full_n;
wire    myproject_U0_start_write;
wire    Block_myproject_axi_exit1109_proc_U0_start_full_n;
wire    Block_myproject_axi_exit1109_proc_U0_start_write;

Block_codeRepl1107_proc46 Block_codeRepl1107_proc46_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_codeRepl1107_proc46_U0_ap_start),
    .start_full_n(Block_codeRepl1107_proc46_U0_start_full_n),
    .ap_done(Block_codeRepl1107_proc46_U0_ap_done),
    .ap_continue(Block_codeRepl1107_proc46_U0_ap_continue),
    .ap_idle(Block_codeRepl1107_proc46_U0_ap_idle),
    .ap_ready(Block_codeRepl1107_proc46_U0_ap_ready),
    .start_out(Block_codeRepl1107_proc46_U0_start_out),
    .start_write(Block_codeRepl1107_proc46_U0_start_write),
    .in_r_TLAST(in_r_TLAST),
    .in_r_TVALID(in_r_TVALID),
    .in_r_TREADY(Block_codeRepl1107_proc46_U0_in_r_TREADY),
    .in_r_TDATA(in_r_TDATA),
    .in_local_V_data_V_0_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_0_din),
    .in_local_V_data_V_0_full_n(in_local_V_data_V_0_full_n),
    .in_local_V_data_V_0_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_0_write),
    .in_local_V_data_V_1_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_1_din),
    .in_local_V_data_V_1_full_n(in_local_V_data_V_1_full_n),
    .in_local_V_data_V_1_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_1_write),
    .in_local_V_data_V_2_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_2_din),
    .in_local_V_data_V_2_full_n(in_local_V_data_V_2_full_n),
    .in_local_V_data_V_2_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_2_write),
    .in_local_V_data_V_3_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_3_din),
    .in_local_V_data_V_3_full_n(in_local_V_data_V_3_full_n),
    .in_local_V_data_V_3_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_3_write),
    .in_local_V_data_V_4_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_4_din),
    .in_local_V_data_V_4_full_n(in_local_V_data_V_4_full_n),
    .in_local_V_data_V_4_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_4_write),
    .in_local_V_data_V_5_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_5_din),
    .in_local_V_data_V_5_full_n(in_local_V_data_V_5_full_n),
    .in_local_V_data_V_5_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_5_write),
    .in_local_V_data_V_6_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_6_din),
    .in_local_V_data_V_6_full_n(in_local_V_data_V_6_full_n),
    .in_local_V_data_V_6_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_6_write),
    .in_local_V_data_V_7_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_7_din),
    .in_local_V_data_V_7_full_n(in_local_V_data_V_7_full_n),
    .in_local_V_data_V_7_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_7_write),
    .in_local_V_data_V_8_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_8_din),
    .in_local_V_data_V_8_full_n(in_local_V_data_V_8_full_n),
    .in_local_V_data_V_8_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_8_write),
    .in_local_V_data_V_9_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_9_din),
    .in_local_V_data_V_9_full_n(in_local_V_data_V_9_full_n),
    .in_local_V_data_V_9_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_9_write),
    .in_local_V_data_V_10_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_10_din),
    .in_local_V_data_V_10_full_n(in_local_V_data_V_10_full_n),
    .in_local_V_data_V_10_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_10_write),
    .in_local_V_data_V_11_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_11_din),
    .in_local_V_data_V_11_full_n(in_local_V_data_V_11_full_n),
    .in_local_V_data_V_11_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_11_write),
    .in_local_V_data_V_12_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_12_din),
    .in_local_V_data_V_12_full_n(in_local_V_data_V_12_full_n),
    .in_local_V_data_V_12_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_12_write),
    .in_local_V_data_V_13_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_13_din),
    .in_local_V_data_V_13_full_n(in_local_V_data_V_13_full_n),
    .in_local_V_data_V_13_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_13_write),
    .in_local_V_data_V_14_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_14_din),
    .in_local_V_data_V_14_full_n(in_local_V_data_V_14_full_n),
    .in_local_V_data_V_14_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_14_write),
    .in_local_V_data_V_15_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_15_din),
    .in_local_V_data_V_15_full_n(in_local_V_data_V_15_full_n),
    .in_local_V_data_V_15_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_15_write),
    .in_local_V_data_V_16_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_16_din),
    .in_local_V_data_V_16_full_n(in_local_V_data_V_16_full_n),
    .in_local_V_data_V_16_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_16_write),
    .in_local_V_data_V_17_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_17_din),
    .in_local_V_data_V_17_full_n(in_local_V_data_V_17_full_n),
    .in_local_V_data_V_17_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_17_write),
    .in_local_V_data_V_18_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_18_din),
    .in_local_V_data_V_18_full_n(in_local_V_data_V_18_full_n),
    .in_local_V_data_V_18_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_18_write),
    .in_local_V_data_V_19_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_19_din),
    .in_local_V_data_V_19_full_n(in_local_V_data_V_19_full_n),
    .in_local_V_data_V_19_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_19_write),
    .in_local_V_data_V_20_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_20_din),
    .in_local_V_data_V_20_full_n(in_local_V_data_V_20_full_n),
    .in_local_V_data_V_20_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_20_write),
    .in_local_V_data_V_21_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_21_din),
    .in_local_V_data_V_21_full_n(in_local_V_data_V_21_full_n),
    .in_local_V_data_V_21_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_21_write),
    .in_local_V_data_V_22_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_22_din),
    .in_local_V_data_V_22_full_n(in_local_V_data_V_22_full_n),
    .in_local_V_data_V_22_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_22_write),
    .in_local_V_data_V_23_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_23_din),
    .in_local_V_data_V_23_full_n(in_local_V_data_V_23_full_n),
    .in_local_V_data_V_23_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_23_write),
    .in_local_V_data_V_24_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_24_din),
    .in_local_V_data_V_24_full_n(in_local_V_data_V_24_full_n),
    .in_local_V_data_V_24_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_24_write),
    .in_local_V_data_V_25_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_25_din),
    .in_local_V_data_V_25_full_n(in_local_V_data_V_25_full_n),
    .in_local_V_data_V_25_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_25_write),
    .in_local_V_data_V_26_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_26_din),
    .in_local_V_data_V_26_full_n(in_local_V_data_V_26_full_n),
    .in_local_V_data_V_26_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_26_write),
    .in_local_V_data_V_27_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_27_din),
    .in_local_V_data_V_27_full_n(in_local_V_data_V_27_full_n),
    .in_local_V_data_V_27_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_27_write),
    .in_local_V_data_V_28_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_28_din),
    .in_local_V_data_V_28_full_n(in_local_V_data_V_28_full_n),
    .in_local_V_data_V_28_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_28_write),
    .in_local_V_data_V_29_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_29_din),
    .in_local_V_data_V_29_full_n(in_local_V_data_V_29_full_n),
    .in_local_V_data_V_29_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_29_write),
    .in_local_V_data_V_30_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_30_din),
    .in_local_V_data_V_30_full_n(in_local_V_data_V_30_full_n),
    .in_local_V_data_V_30_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_30_write),
    .in_local_V_data_V_31_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_31_din),
    .in_local_V_data_V_31_full_n(in_local_V_data_V_31_full_n),
    .in_local_V_data_V_31_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_31_write),
    .is_last_1_i_0_out_out_din(Block_codeRepl1107_proc46_U0_is_last_1_i_0_out_out_din),
    .is_last_1_i_0_out_out_full_n(is_last_1_i_0_loc_c_full_n),
    .is_last_1_i_0_out_out_write(Block_codeRepl1107_proc46_U0_is_last_1_i_0_out_out_write)
);

myproject myproject_U0(
    .input_1_V_data_0_V_dout(in_local_V_data_V_0_dout),
    .input_1_V_data_0_V_empty_n(in_local_V_data_V_0_empty_n),
    .input_1_V_data_0_V_read(myproject_U0_input_1_V_data_0_V_read),
    .input_1_V_data_1_V_dout(in_local_V_data_V_1_dout),
    .input_1_V_data_1_V_empty_n(in_local_V_data_V_1_empty_n),
    .input_1_V_data_1_V_read(myproject_U0_input_1_V_data_1_V_read),
    .input_1_V_data_2_V_dout(in_local_V_data_V_2_dout),
    .input_1_V_data_2_V_empty_n(in_local_V_data_V_2_empty_n),
    .input_1_V_data_2_V_read(myproject_U0_input_1_V_data_2_V_read),
    .input_1_V_data_3_V_dout(in_local_V_data_V_3_dout),
    .input_1_V_data_3_V_empty_n(in_local_V_data_V_3_empty_n),
    .input_1_V_data_3_V_read(myproject_U0_input_1_V_data_3_V_read),
    .input_1_V_data_4_V_dout(in_local_V_data_V_4_dout),
    .input_1_V_data_4_V_empty_n(in_local_V_data_V_4_empty_n),
    .input_1_V_data_4_V_read(myproject_U0_input_1_V_data_4_V_read),
    .input_1_V_data_5_V_dout(in_local_V_data_V_5_dout),
    .input_1_V_data_5_V_empty_n(in_local_V_data_V_5_empty_n),
    .input_1_V_data_5_V_read(myproject_U0_input_1_V_data_5_V_read),
    .input_1_V_data_6_V_dout(in_local_V_data_V_6_dout),
    .input_1_V_data_6_V_empty_n(in_local_V_data_V_6_empty_n),
    .input_1_V_data_6_V_read(myproject_U0_input_1_V_data_6_V_read),
    .input_1_V_data_7_V_dout(in_local_V_data_V_7_dout),
    .input_1_V_data_7_V_empty_n(in_local_V_data_V_7_empty_n),
    .input_1_V_data_7_V_read(myproject_U0_input_1_V_data_7_V_read),
    .input_1_V_data_8_V_dout(in_local_V_data_V_8_dout),
    .input_1_V_data_8_V_empty_n(in_local_V_data_V_8_empty_n),
    .input_1_V_data_8_V_read(myproject_U0_input_1_V_data_8_V_read),
    .input_1_V_data_9_V_dout(in_local_V_data_V_9_dout),
    .input_1_V_data_9_V_empty_n(in_local_V_data_V_9_empty_n),
    .input_1_V_data_9_V_read(myproject_U0_input_1_V_data_9_V_read),
    .input_1_V_data_10_V_dout(in_local_V_data_V_10_dout),
    .input_1_V_data_10_V_empty_n(in_local_V_data_V_10_empty_n),
    .input_1_V_data_10_V_read(myproject_U0_input_1_V_data_10_V_read),
    .input_1_V_data_11_V_dout(in_local_V_data_V_11_dout),
    .input_1_V_data_11_V_empty_n(in_local_V_data_V_11_empty_n),
    .input_1_V_data_11_V_read(myproject_U0_input_1_V_data_11_V_read),
    .input_1_V_data_12_V_dout(in_local_V_data_V_12_dout),
    .input_1_V_data_12_V_empty_n(in_local_V_data_V_12_empty_n),
    .input_1_V_data_12_V_read(myproject_U0_input_1_V_data_12_V_read),
    .input_1_V_data_13_V_dout(in_local_V_data_V_13_dout),
    .input_1_V_data_13_V_empty_n(in_local_V_data_V_13_empty_n),
    .input_1_V_data_13_V_read(myproject_U0_input_1_V_data_13_V_read),
    .input_1_V_data_14_V_dout(in_local_V_data_V_14_dout),
    .input_1_V_data_14_V_empty_n(in_local_V_data_V_14_empty_n),
    .input_1_V_data_14_V_read(myproject_U0_input_1_V_data_14_V_read),
    .input_1_V_data_15_V_dout(in_local_V_data_V_15_dout),
    .input_1_V_data_15_V_empty_n(in_local_V_data_V_15_empty_n),
    .input_1_V_data_15_V_read(myproject_U0_input_1_V_data_15_V_read),
    .input_1_V_data_16_V_dout(in_local_V_data_V_16_dout),
    .input_1_V_data_16_V_empty_n(in_local_V_data_V_16_empty_n),
    .input_1_V_data_16_V_read(myproject_U0_input_1_V_data_16_V_read),
    .input_1_V_data_17_V_dout(in_local_V_data_V_17_dout),
    .input_1_V_data_17_V_empty_n(in_local_V_data_V_17_empty_n),
    .input_1_V_data_17_V_read(myproject_U0_input_1_V_data_17_V_read),
    .input_1_V_data_18_V_dout(in_local_V_data_V_18_dout),
    .input_1_V_data_18_V_empty_n(in_local_V_data_V_18_empty_n),
    .input_1_V_data_18_V_read(myproject_U0_input_1_V_data_18_V_read),
    .input_1_V_data_19_V_dout(in_local_V_data_V_19_dout),
    .input_1_V_data_19_V_empty_n(in_local_V_data_V_19_empty_n),
    .input_1_V_data_19_V_read(myproject_U0_input_1_V_data_19_V_read),
    .input_1_V_data_20_V_dout(in_local_V_data_V_20_dout),
    .input_1_V_data_20_V_empty_n(in_local_V_data_V_20_empty_n),
    .input_1_V_data_20_V_read(myproject_U0_input_1_V_data_20_V_read),
    .input_1_V_data_21_V_dout(in_local_V_data_V_21_dout),
    .input_1_V_data_21_V_empty_n(in_local_V_data_V_21_empty_n),
    .input_1_V_data_21_V_read(myproject_U0_input_1_V_data_21_V_read),
    .input_1_V_data_22_V_dout(in_local_V_data_V_22_dout),
    .input_1_V_data_22_V_empty_n(in_local_V_data_V_22_empty_n),
    .input_1_V_data_22_V_read(myproject_U0_input_1_V_data_22_V_read),
    .input_1_V_data_23_V_dout(in_local_V_data_V_23_dout),
    .input_1_V_data_23_V_empty_n(in_local_V_data_V_23_empty_n),
    .input_1_V_data_23_V_read(myproject_U0_input_1_V_data_23_V_read),
    .input_1_V_data_24_V_dout(in_local_V_data_V_24_dout),
    .input_1_V_data_24_V_empty_n(in_local_V_data_V_24_empty_n),
    .input_1_V_data_24_V_read(myproject_U0_input_1_V_data_24_V_read),
    .input_1_V_data_25_V_dout(in_local_V_data_V_25_dout),
    .input_1_V_data_25_V_empty_n(in_local_V_data_V_25_empty_n),
    .input_1_V_data_25_V_read(myproject_U0_input_1_V_data_25_V_read),
    .input_1_V_data_26_V_dout(in_local_V_data_V_26_dout),
    .input_1_V_data_26_V_empty_n(in_local_V_data_V_26_empty_n),
    .input_1_V_data_26_V_read(myproject_U0_input_1_V_data_26_V_read),
    .input_1_V_data_27_V_dout(in_local_V_data_V_27_dout),
    .input_1_V_data_27_V_empty_n(in_local_V_data_V_27_empty_n),
    .input_1_V_data_27_V_read(myproject_U0_input_1_V_data_27_V_read),
    .input_1_V_data_28_V_dout(in_local_V_data_V_28_dout),
    .input_1_V_data_28_V_empty_n(in_local_V_data_V_28_empty_n),
    .input_1_V_data_28_V_read(myproject_U0_input_1_V_data_28_V_read),
    .input_1_V_data_29_V_dout(in_local_V_data_V_29_dout),
    .input_1_V_data_29_V_empty_n(in_local_V_data_V_29_empty_n),
    .input_1_V_data_29_V_read(myproject_U0_input_1_V_data_29_V_read),
    .input_1_V_data_30_V_dout(in_local_V_data_V_30_dout),
    .input_1_V_data_30_V_empty_n(in_local_V_data_V_30_empty_n),
    .input_1_V_data_30_V_read(myproject_U0_input_1_V_data_30_V_read),
    .input_1_V_data_31_V_dout(in_local_V_data_V_31_dout),
    .input_1_V_data_31_V_empty_n(in_local_V_data_V_31_empty_n),
    .input_1_V_data_31_V_read(myproject_U0_input_1_V_data_31_V_read),
    .layer2_out_V_data_V_din(myproject_U0_layer2_out_V_data_V_din),
    .layer2_out_V_data_V_full_n(out_local_V_data_0_V_full_n),
    .layer2_out_V_data_V_write(myproject_U0_layer2_out_V_data_V_write),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(myproject_U0_ap_start),
    .ap_done(myproject_U0_ap_done),
    .ap_ready(myproject_U0_ap_ready),
    .ap_idle(myproject_U0_ap_idle),
    .ap_continue(myproject_U0_ap_continue)
);

Block_myproject_axi_exit1109_proc Block_myproject_axi_exit1109_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_myproject_axi_exit1109_proc_U0_ap_start),
    .ap_done(Block_myproject_axi_exit1109_proc_U0_ap_done),
    .ap_continue(Block_myproject_axi_exit1109_proc_U0_ap_continue),
    .ap_idle(Block_myproject_axi_exit1109_proc_U0_ap_idle),
    .ap_ready(Block_myproject_axi_exit1109_proc_U0_ap_ready),
    .out_local_V_data_0_V_dout(out_local_V_data_0_V_dout),
    .out_local_V_data_0_V_empty_n(out_local_V_data_0_V_empty_n),
    .out_local_V_data_0_V_read(Block_myproject_axi_exit1109_proc_U0_out_local_V_data_0_V_read),
    .out_r_TDATA(Block_myproject_axi_exit1109_proc_U0_out_r_TDATA),
    .out_r_TVALID(Block_myproject_axi_exit1109_proc_U0_out_r_TVALID),
    .out_r_TREADY(out_r_TREADY),
    .out_r_TLAST(Block_myproject_axi_exit1109_proc_U0_out_r_TLAST),
    .is_last_1_i_0_loc_dout(is_last_1_i_0_loc_c_dout),
    .is_last_1_i_0_loc_empty_n(is_last_1_i_0_loc_c_empty_n),
    .is_last_1_i_0_loc_read(Block_myproject_axi_exit1109_proc_U0_is_last_1_i_0_loc_read)
);

fifo_w32_d1_A in_local_V_data_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_0_din),
    .if_full_n(in_local_V_data_V_0_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_0_write),
    .if_dout(in_local_V_data_V_0_dout),
    .if_empty_n(in_local_V_data_V_0_empty_n),
    .if_read(myproject_U0_input_1_V_data_0_V_read)
);

fifo_w32_d1_A in_local_V_data_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_1_din),
    .if_full_n(in_local_V_data_V_1_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_1_write),
    .if_dout(in_local_V_data_V_1_dout),
    .if_empty_n(in_local_V_data_V_1_empty_n),
    .if_read(myproject_U0_input_1_V_data_1_V_read)
);

fifo_w32_d1_A in_local_V_data_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_2_din),
    .if_full_n(in_local_V_data_V_2_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_2_write),
    .if_dout(in_local_V_data_V_2_dout),
    .if_empty_n(in_local_V_data_V_2_empty_n),
    .if_read(myproject_U0_input_1_V_data_2_V_read)
);

fifo_w32_d1_A in_local_V_data_V_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_3_din),
    .if_full_n(in_local_V_data_V_3_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_3_write),
    .if_dout(in_local_V_data_V_3_dout),
    .if_empty_n(in_local_V_data_V_3_empty_n),
    .if_read(myproject_U0_input_1_V_data_3_V_read)
);

fifo_w32_d1_A in_local_V_data_V_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_4_din),
    .if_full_n(in_local_V_data_V_4_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_4_write),
    .if_dout(in_local_V_data_V_4_dout),
    .if_empty_n(in_local_V_data_V_4_empty_n),
    .if_read(myproject_U0_input_1_V_data_4_V_read)
);

fifo_w32_d1_A in_local_V_data_V_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_5_din),
    .if_full_n(in_local_V_data_V_5_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_5_write),
    .if_dout(in_local_V_data_V_5_dout),
    .if_empty_n(in_local_V_data_V_5_empty_n),
    .if_read(myproject_U0_input_1_V_data_5_V_read)
);

fifo_w32_d1_A in_local_V_data_V_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_6_din),
    .if_full_n(in_local_V_data_V_6_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_6_write),
    .if_dout(in_local_V_data_V_6_dout),
    .if_empty_n(in_local_V_data_V_6_empty_n),
    .if_read(myproject_U0_input_1_V_data_6_V_read)
);

fifo_w32_d1_A in_local_V_data_V_7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_7_din),
    .if_full_n(in_local_V_data_V_7_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_7_write),
    .if_dout(in_local_V_data_V_7_dout),
    .if_empty_n(in_local_V_data_V_7_empty_n),
    .if_read(myproject_U0_input_1_V_data_7_V_read)
);

fifo_w32_d1_A in_local_V_data_V_8_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_8_din),
    .if_full_n(in_local_V_data_V_8_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_8_write),
    .if_dout(in_local_V_data_V_8_dout),
    .if_empty_n(in_local_V_data_V_8_empty_n),
    .if_read(myproject_U0_input_1_V_data_8_V_read)
);

fifo_w32_d1_A in_local_V_data_V_9_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_9_din),
    .if_full_n(in_local_V_data_V_9_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_9_write),
    .if_dout(in_local_V_data_V_9_dout),
    .if_empty_n(in_local_V_data_V_9_empty_n),
    .if_read(myproject_U0_input_1_V_data_9_V_read)
);

fifo_w32_d1_A in_local_V_data_V_10_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_10_din),
    .if_full_n(in_local_V_data_V_10_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_10_write),
    .if_dout(in_local_V_data_V_10_dout),
    .if_empty_n(in_local_V_data_V_10_empty_n),
    .if_read(myproject_U0_input_1_V_data_10_V_read)
);

fifo_w32_d1_A in_local_V_data_V_11_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_11_din),
    .if_full_n(in_local_V_data_V_11_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_11_write),
    .if_dout(in_local_V_data_V_11_dout),
    .if_empty_n(in_local_V_data_V_11_empty_n),
    .if_read(myproject_U0_input_1_V_data_11_V_read)
);

fifo_w32_d1_A in_local_V_data_V_12_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_12_din),
    .if_full_n(in_local_V_data_V_12_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_12_write),
    .if_dout(in_local_V_data_V_12_dout),
    .if_empty_n(in_local_V_data_V_12_empty_n),
    .if_read(myproject_U0_input_1_V_data_12_V_read)
);

fifo_w32_d1_A in_local_V_data_V_13_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_13_din),
    .if_full_n(in_local_V_data_V_13_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_13_write),
    .if_dout(in_local_V_data_V_13_dout),
    .if_empty_n(in_local_V_data_V_13_empty_n),
    .if_read(myproject_U0_input_1_V_data_13_V_read)
);

fifo_w32_d1_A in_local_V_data_V_14_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_14_din),
    .if_full_n(in_local_V_data_V_14_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_14_write),
    .if_dout(in_local_V_data_V_14_dout),
    .if_empty_n(in_local_V_data_V_14_empty_n),
    .if_read(myproject_U0_input_1_V_data_14_V_read)
);

fifo_w32_d1_A in_local_V_data_V_15_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_15_din),
    .if_full_n(in_local_V_data_V_15_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_15_write),
    .if_dout(in_local_V_data_V_15_dout),
    .if_empty_n(in_local_V_data_V_15_empty_n),
    .if_read(myproject_U0_input_1_V_data_15_V_read)
);

fifo_w32_d1_A in_local_V_data_V_16_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_16_din),
    .if_full_n(in_local_V_data_V_16_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_16_write),
    .if_dout(in_local_V_data_V_16_dout),
    .if_empty_n(in_local_V_data_V_16_empty_n),
    .if_read(myproject_U0_input_1_V_data_16_V_read)
);

fifo_w32_d1_A in_local_V_data_V_17_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_17_din),
    .if_full_n(in_local_V_data_V_17_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_17_write),
    .if_dout(in_local_V_data_V_17_dout),
    .if_empty_n(in_local_V_data_V_17_empty_n),
    .if_read(myproject_U0_input_1_V_data_17_V_read)
);

fifo_w32_d1_A in_local_V_data_V_18_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_18_din),
    .if_full_n(in_local_V_data_V_18_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_18_write),
    .if_dout(in_local_V_data_V_18_dout),
    .if_empty_n(in_local_V_data_V_18_empty_n),
    .if_read(myproject_U0_input_1_V_data_18_V_read)
);

fifo_w32_d1_A in_local_V_data_V_19_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_19_din),
    .if_full_n(in_local_V_data_V_19_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_19_write),
    .if_dout(in_local_V_data_V_19_dout),
    .if_empty_n(in_local_V_data_V_19_empty_n),
    .if_read(myproject_U0_input_1_V_data_19_V_read)
);

fifo_w32_d1_A in_local_V_data_V_20_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_20_din),
    .if_full_n(in_local_V_data_V_20_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_20_write),
    .if_dout(in_local_V_data_V_20_dout),
    .if_empty_n(in_local_V_data_V_20_empty_n),
    .if_read(myproject_U0_input_1_V_data_20_V_read)
);

fifo_w32_d1_A in_local_V_data_V_21_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_21_din),
    .if_full_n(in_local_V_data_V_21_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_21_write),
    .if_dout(in_local_V_data_V_21_dout),
    .if_empty_n(in_local_V_data_V_21_empty_n),
    .if_read(myproject_U0_input_1_V_data_21_V_read)
);

fifo_w32_d1_A in_local_V_data_V_22_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_22_din),
    .if_full_n(in_local_V_data_V_22_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_22_write),
    .if_dout(in_local_V_data_V_22_dout),
    .if_empty_n(in_local_V_data_V_22_empty_n),
    .if_read(myproject_U0_input_1_V_data_22_V_read)
);

fifo_w32_d1_A in_local_V_data_V_23_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_23_din),
    .if_full_n(in_local_V_data_V_23_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_23_write),
    .if_dout(in_local_V_data_V_23_dout),
    .if_empty_n(in_local_V_data_V_23_empty_n),
    .if_read(myproject_U0_input_1_V_data_23_V_read)
);

fifo_w32_d1_A in_local_V_data_V_24_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_24_din),
    .if_full_n(in_local_V_data_V_24_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_24_write),
    .if_dout(in_local_V_data_V_24_dout),
    .if_empty_n(in_local_V_data_V_24_empty_n),
    .if_read(myproject_U0_input_1_V_data_24_V_read)
);

fifo_w32_d1_A in_local_V_data_V_25_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_25_din),
    .if_full_n(in_local_V_data_V_25_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_25_write),
    .if_dout(in_local_V_data_V_25_dout),
    .if_empty_n(in_local_V_data_V_25_empty_n),
    .if_read(myproject_U0_input_1_V_data_25_V_read)
);

fifo_w32_d1_A in_local_V_data_V_26_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_26_din),
    .if_full_n(in_local_V_data_V_26_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_26_write),
    .if_dout(in_local_V_data_V_26_dout),
    .if_empty_n(in_local_V_data_V_26_empty_n),
    .if_read(myproject_U0_input_1_V_data_26_V_read)
);

fifo_w32_d1_A in_local_V_data_V_27_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_27_din),
    .if_full_n(in_local_V_data_V_27_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_27_write),
    .if_dout(in_local_V_data_V_27_dout),
    .if_empty_n(in_local_V_data_V_27_empty_n),
    .if_read(myproject_U0_input_1_V_data_27_V_read)
);

fifo_w32_d1_A in_local_V_data_V_28_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_28_din),
    .if_full_n(in_local_V_data_V_28_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_28_write),
    .if_dout(in_local_V_data_V_28_dout),
    .if_empty_n(in_local_V_data_V_28_empty_n),
    .if_read(myproject_U0_input_1_V_data_28_V_read)
);

fifo_w32_d1_A in_local_V_data_V_29_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_29_din),
    .if_full_n(in_local_V_data_V_29_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_29_write),
    .if_dout(in_local_V_data_V_29_dout),
    .if_empty_n(in_local_V_data_V_29_empty_n),
    .if_read(myproject_U0_input_1_V_data_29_V_read)
);

fifo_w32_d1_A in_local_V_data_V_30_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_30_din),
    .if_full_n(in_local_V_data_V_30_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_30_write),
    .if_dout(in_local_V_data_V_30_dout),
    .if_empty_n(in_local_V_data_V_30_empty_n),
    .if_read(myproject_U0_input_1_V_data_30_V_read)
);

fifo_w32_d1_A in_local_V_data_V_31_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_in_local_V_data_V_31_din),
    .if_full_n(in_local_V_data_V_31_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_in_local_V_data_V_31_write),
    .if_dout(in_local_V_data_V_31_dout),
    .if_empty_n(in_local_V_data_V_31_empty_n),
    .if_read(myproject_U0_input_1_V_data_31_V_read)
);

fifo_w1_d3_A is_last_1_i_0_loc_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl1107_proc46_U0_is_last_1_i_0_out_out_din),
    .if_full_n(is_last_1_i_0_loc_c_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_is_last_1_i_0_out_out_write),
    .if_dout(is_last_1_i_0_loc_c_dout),
    .if_empty_n(is_last_1_i_0_loc_c_empty_n),
    .if_read(Block_myproject_axi_exit1109_proc_U0_is_last_1_i_0_loc_read)
);

fifo_w32_d1_A out_local_V_data_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(myproject_U0_layer2_out_V_data_V_din),
    .if_full_n(out_local_V_data_0_V_full_n),
    .if_write(myproject_U0_layer2_out_V_data_V_write),
    .if_dout(out_local_V_data_0_V_dout),
    .if_empty_n(out_local_V_data_0_V_empty_n),
    .if_read(Block_myproject_axi_exit1109_proc_U0_out_local_V_data_0_V_read)
);

start_for_myproject_U0 start_for_myproject_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_myproject_U0_din),
    .if_full_n(start_for_myproject_U0_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_start_write),
    .if_dout(start_for_myproject_U0_dout),
    .if_empty_n(start_for_myproject_U0_empty_n),
    .if_read(myproject_U0_ap_ready)
);

start_for_Block_myproject_axi_exit1109_proc_U0 start_for_Block_myproject_axi_exit1109_proc_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Block_myproject_axi_exit1109_proc_U0_din),
    .if_full_n(start_for_Block_myproject_axi_exit1109_proc_U0_full_n),
    .if_write(Block_codeRepl1107_proc46_U0_start_write),
    .if_dout(start_for_Block_myproject_axi_exit1109_proc_U0_dout),
    .if_empty_n(start_for_Block_myproject_axi_exit1109_proc_U0_empty_n),
    .if_read(Block_myproject_axi_exit1109_proc_U0_ap_ready)
);

assign Block_codeRepl1107_proc46_U0_ap_continue = 1'b1;

assign Block_codeRepl1107_proc46_U0_ap_start = 1'b1;

assign Block_codeRepl1107_proc46_U0_start_full_n = (start_for_myproject_U0_full_n & start_for_Block_myproject_axi_exit1109_proc_U0_full_n);

assign Block_myproject_axi_exit1109_proc_U0_ap_continue = 1'b1;

assign Block_myproject_axi_exit1109_proc_U0_ap_start = start_for_Block_myproject_axi_exit1109_proc_U0_empty_n;

assign Block_myproject_axi_exit1109_proc_U0_start_full_n = 1'b1;

assign Block_myproject_axi_exit1109_proc_U0_start_write = 1'b0;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b0;

assign in_r_TREADY = Block_codeRepl1107_proc46_U0_in_r_TREADY;

assign myproject_U0_ap_continue = 1'b1;

assign myproject_U0_ap_start = start_for_myproject_U0_empty_n;

assign myproject_U0_start_full_n = 1'b1;

assign myproject_U0_start_write = 1'b0;

assign out_r_TDATA = Block_myproject_axi_exit1109_proc_U0_out_r_TDATA;

assign out_r_TLAST = Block_myproject_axi_exit1109_proc_U0_out_r_TLAST;

assign out_r_TVALID = Block_myproject_axi_exit1109_proc_U0_out_r_TVALID;

assign start_for_Block_myproject_axi_exit1109_proc_U0_din = 1'b1;

assign start_for_myproject_U0_din = 1'b1;

endmodule //myproject_axi
