Backend: Vivado
ClockPeriod: 5
HLSConfig:
  LayerName:
    focus:
      Precision:
        result: ap_fixed<32,16>
      Trace: false
    input_1:
      Precision:
        result: ap_fixed<32,16>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: ap_fixed<32,16>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_stream
InputData: null
KerasModel: !keras_model '../Lab3//hls_model/keras_model.h5'
OutputDir: ../Lab3//hls_model
OutputPredictions: null
Part: xc7z020clg400-1
ProjectName: myproject
Stamp: FDa0f52b
