AcceleratorConfig:
  Board: pynq-z2
  Driver: python
  Interface: axi_stream
  Precision:
    Input: float
    Output: float
Backend: VivadoAccelerator
ClockPeriod: 5
HLSConfig:
  LayerName:
    dot_product:
      Precision:
        result: ap_fixed<32,16>
      Trace: false
    input_1:
      Precision:
        result: ap_fixed<32,16>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: ap_fixed<32,16>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_stream
InputData: null
KerasModel: !keras_model './hls_model/dotproduct_axi/keras_model.h5'
OutputDir: ./hls_model/dotproduct_axi
OutputPredictions: null
Part: xc7z020clg400-1
ProjectName: myproject
Stamp: c9C09D68
