// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _myproject_HH_
#define _myproject_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "myproject_Block_preheader_i_i_033_proc45.h"
#include "myproject_Loop_1_proc.h"
#include "myproject_Block_dot_product_array_array_ap_fixed_1u_config2_exit_proc.h"
#include "fifo_w32_d32_A.h"
#include "fifo_w32_d2_A.h"
#include "start_for_myproject_Loop_1_proc_U0.h"

namespace ap_rtl {

struct myproject : public sc_module {
    // Port declarations 106
    sc_in< sc_lv<32> > input_1_V_data_0_V_dout;
    sc_in< sc_logic > input_1_V_data_0_V_empty_n;
    sc_out< sc_logic > input_1_V_data_0_V_read;
    sc_in< sc_lv<32> > input_1_V_data_1_V_dout;
    sc_in< sc_logic > input_1_V_data_1_V_empty_n;
    sc_out< sc_logic > input_1_V_data_1_V_read;
    sc_in< sc_lv<32> > input_1_V_data_2_V_dout;
    sc_in< sc_logic > input_1_V_data_2_V_empty_n;
    sc_out< sc_logic > input_1_V_data_2_V_read;
    sc_in< sc_lv<32> > input_1_V_data_3_V_dout;
    sc_in< sc_logic > input_1_V_data_3_V_empty_n;
    sc_out< sc_logic > input_1_V_data_3_V_read;
    sc_in< sc_lv<32> > input_1_V_data_4_V_dout;
    sc_in< sc_logic > input_1_V_data_4_V_empty_n;
    sc_out< sc_logic > input_1_V_data_4_V_read;
    sc_in< sc_lv<32> > input_1_V_data_5_V_dout;
    sc_in< sc_logic > input_1_V_data_5_V_empty_n;
    sc_out< sc_logic > input_1_V_data_5_V_read;
    sc_in< sc_lv<32> > input_1_V_data_6_V_dout;
    sc_in< sc_logic > input_1_V_data_6_V_empty_n;
    sc_out< sc_logic > input_1_V_data_6_V_read;
    sc_in< sc_lv<32> > input_1_V_data_7_V_dout;
    sc_in< sc_logic > input_1_V_data_7_V_empty_n;
    sc_out< sc_logic > input_1_V_data_7_V_read;
    sc_in< sc_lv<32> > input_1_V_data_8_V_dout;
    sc_in< sc_logic > input_1_V_data_8_V_empty_n;
    sc_out< sc_logic > input_1_V_data_8_V_read;
    sc_in< sc_lv<32> > input_1_V_data_9_V_dout;
    sc_in< sc_logic > input_1_V_data_9_V_empty_n;
    sc_out< sc_logic > input_1_V_data_9_V_read;
    sc_in< sc_lv<32> > input_1_V_data_10_V_dout;
    sc_in< sc_logic > input_1_V_data_10_V_empty_n;
    sc_out< sc_logic > input_1_V_data_10_V_read;
    sc_in< sc_lv<32> > input_1_V_data_11_V_dout;
    sc_in< sc_logic > input_1_V_data_11_V_empty_n;
    sc_out< sc_logic > input_1_V_data_11_V_read;
    sc_in< sc_lv<32> > input_1_V_data_12_V_dout;
    sc_in< sc_logic > input_1_V_data_12_V_empty_n;
    sc_out< sc_logic > input_1_V_data_12_V_read;
    sc_in< sc_lv<32> > input_1_V_data_13_V_dout;
    sc_in< sc_logic > input_1_V_data_13_V_empty_n;
    sc_out< sc_logic > input_1_V_data_13_V_read;
    sc_in< sc_lv<32> > input_1_V_data_14_V_dout;
    sc_in< sc_logic > input_1_V_data_14_V_empty_n;
    sc_out< sc_logic > input_1_V_data_14_V_read;
    sc_in< sc_lv<32> > input_1_V_data_15_V_dout;
    sc_in< sc_logic > input_1_V_data_15_V_empty_n;
    sc_out< sc_logic > input_1_V_data_15_V_read;
    sc_in< sc_lv<32> > input_1_V_data_16_V_dout;
    sc_in< sc_logic > input_1_V_data_16_V_empty_n;
    sc_out< sc_logic > input_1_V_data_16_V_read;
    sc_in< sc_lv<32> > input_1_V_data_17_V_dout;
    sc_in< sc_logic > input_1_V_data_17_V_empty_n;
    sc_out< sc_logic > input_1_V_data_17_V_read;
    sc_in< sc_lv<32> > input_1_V_data_18_V_dout;
    sc_in< sc_logic > input_1_V_data_18_V_empty_n;
    sc_out< sc_logic > input_1_V_data_18_V_read;
    sc_in< sc_lv<32> > input_1_V_data_19_V_dout;
    sc_in< sc_logic > input_1_V_data_19_V_empty_n;
    sc_out< sc_logic > input_1_V_data_19_V_read;
    sc_in< sc_lv<32> > input_1_V_data_20_V_dout;
    sc_in< sc_logic > input_1_V_data_20_V_empty_n;
    sc_out< sc_logic > input_1_V_data_20_V_read;
    sc_in< sc_lv<32> > input_1_V_data_21_V_dout;
    sc_in< sc_logic > input_1_V_data_21_V_empty_n;
    sc_out< sc_logic > input_1_V_data_21_V_read;
    sc_in< sc_lv<32> > input_1_V_data_22_V_dout;
    sc_in< sc_logic > input_1_V_data_22_V_empty_n;
    sc_out< sc_logic > input_1_V_data_22_V_read;
    sc_in< sc_lv<32> > input_1_V_data_23_V_dout;
    sc_in< sc_logic > input_1_V_data_23_V_empty_n;
    sc_out< sc_logic > input_1_V_data_23_V_read;
    sc_in< sc_lv<32> > input_1_V_data_24_V_dout;
    sc_in< sc_logic > input_1_V_data_24_V_empty_n;
    sc_out< sc_logic > input_1_V_data_24_V_read;
    sc_in< sc_lv<32> > input_1_V_data_25_V_dout;
    sc_in< sc_logic > input_1_V_data_25_V_empty_n;
    sc_out< sc_logic > input_1_V_data_25_V_read;
    sc_in< sc_lv<32> > input_1_V_data_26_V_dout;
    sc_in< sc_logic > input_1_V_data_26_V_empty_n;
    sc_out< sc_logic > input_1_V_data_26_V_read;
    sc_in< sc_lv<32> > input_1_V_data_27_V_dout;
    sc_in< sc_logic > input_1_V_data_27_V_empty_n;
    sc_out< sc_logic > input_1_V_data_27_V_read;
    sc_in< sc_lv<32> > input_1_V_data_28_V_dout;
    sc_in< sc_logic > input_1_V_data_28_V_empty_n;
    sc_out< sc_logic > input_1_V_data_28_V_read;
    sc_in< sc_lv<32> > input_1_V_data_29_V_dout;
    sc_in< sc_logic > input_1_V_data_29_V_empty_n;
    sc_out< sc_logic > input_1_V_data_29_V_read;
    sc_in< sc_lv<32> > input_1_V_data_30_V_dout;
    sc_in< sc_logic > input_1_V_data_30_V_empty_n;
    sc_out< sc_logic > input_1_V_data_30_V_read;
    sc_in< sc_lv<32> > input_1_V_data_31_V_dout;
    sc_in< sc_logic > input_1_V_data_31_V_empty_n;
    sc_out< sc_logic > input_1_V_data_31_V_read;
    sc_out< sc_lv<32> > layer2_out_V_data_V_din;
    sc_in< sc_logic > layer2_out_V_data_V_full_n;
    sc_out< sc_logic > layer2_out_V_data_V_write;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > ap_idle;
    sc_in< sc_logic > ap_continue;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    myproject(sc_module_name name);
    SC_HAS_PROCESS(myproject);

    ~myproject();

    sc_trace_file* mVcdFile;

    myproject_Block_preheader_i_i_033_proc45* myproject_Block_preheader_i_i_033_proc45_U0;
    myproject_Loop_1_proc* myproject_Loop_1_proc_U0;
    myproject_Block_dot_product_array_array_ap_fixed_1u_config2_exit_proc* myproject_Block_dot_product_array_array_ap_fixed_1u_config2_exit_proc_U0;
    fifo_w32_d32_A* tmpdata1_data_V_channel_U;
    fifo_w32_d2_A* p_Val2_loc_channel_U;
    start_for_myproject_Loop_1_proc_U0* start_for_myproject_Loop_1_proc_U0_U;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_ap_start;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_ap_done;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_ap_continue;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_ap_idle;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_ap_ready;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_start_out;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_start_write;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_0_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_1_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_2_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_3_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_4_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_5_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_6_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_7_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_8_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_9_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_10_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_11_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_12_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_13_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_14_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_15_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_16_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_17_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_18_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_19_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_20_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_21_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_22_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_23_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_24_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_25_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_26_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_27_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_28_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_29_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_30_V_read;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_input_1_V_data_31_V_read;
    sc_signal< sc_lv<32> > myproject_Block_preheader_i_i_033_proc45_U0_tmpdata1_data_V_din;
    sc_signal< sc_logic > myproject_Block_preheader_i_i_033_proc45_U0_tmpdata1_data_V_write;
    sc_signal< sc_logic > myproject_Loop_1_proc_U0_ap_start;
    sc_signal< sc_logic > myproject_Loop_1_proc_U0_ap_done;
    sc_signal< sc_logic > myproject_Loop_1_proc_U0_ap_continue;
    sc_signal< sc_logic > myproject_Loop_1_proc_U0_ap_idle;
    sc_signal< sc_logic > myproject_Loop_1_proc_U0_ap_ready;
    sc_signal< sc_logic > myproject_Loop_1_proc_U0_tmpdata1_data_V_read;
    sc_signal< sc_lv<32> > myproject_Loop_1_proc_U0_ap_return;
    sc_signal< sc_logic > ap_channel_done_p_Val2_loc_channel;
    sc_signal< sc_logic > p_Val2_loc_channel_full_n;
    sc_signal< sc_logic > myproject_Block_dot_product_array_array_ap_fixed_1u_config2_exit_proc_U0_ap_start;
    sc_signal< sc_logic > myproject_Block_dot_product_array_array_ap_fixed_1u_config2_exit_proc_U0_ap_done;
    sc_signal< sc_logic > myproject_Block_dot_product_array_array_ap_fixed_1u_config2_exit_proc_U0_ap_continue;
    sc_signal< sc_logic > myproject_Block_dot_product_array_array_ap_fixed_1u_config2_exit_proc_U0_ap_idle;
    sc_signal< sc_logic > myproject_Block_dot_product_array_array_ap_fixed_1u_config2_exit_proc_U0_ap_ready;
    sc_signal< sc_lv<32> > myproject_Block_dot_product_array_array_ap_fixed_1u_config2_exit_proc_U0_layer2_out_V_data_V_din;
    sc_signal< sc_logic > myproject_Block_dot_product_array_array_ap_fixed_1u_config2_exit_proc_U0_layer2_out_V_data_V_write;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > tmpdata1_data_V_channel_full_n;
    sc_signal< sc_lv<32> > tmpdata1_data_V_channel_dout;
    sc_signal< sc_logic > tmpdata1_data_V_channel_empty_n;
    sc_signal< sc_lv<32> > p_Val2_loc_channel_dout;
    sc_signal< sc_logic > p_Val2_loc_channel_empty_n;
    sc_signal< sc_logic > ap_sync_done;
    sc_signal< sc_logic > ap_sync_ready;
    sc_signal< sc_lv<1> > start_for_myproject_Loop_1_proc_U0_din;
    sc_signal< sc_logic > start_for_myproject_Loop_1_proc_U0_full_n;
    sc_signal< sc_lv<1> > start_for_myproject_Loop_1_proc_U0_dout;
    sc_signal< sc_logic > start_for_myproject_Loop_1_proc_U0_empty_n;
    sc_signal< sc_logic > myproject_Loop_1_proc_U0_start_full_n;
    sc_signal< sc_logic > myproject_Loop_1_proc_U0_start_write;
    sc_signal< sc_logic > myproject_Block_dot_product_array_array_ap_fixed_1u_config2_exit_proc_U0_start_full_n;
    sc_signal< sc_logic > myproject_Block_dot_product_array_array_ap_fixed_1u_config2_exit_proc_U0_start_write;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_logic ap_const_logic_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_channel_done_p_Val2_loc_channel();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sync_continue();
    void thread_ap_sync_done();
    void thread_ap_sync_ready();
    void thread_input_1_V_data_0_V_read();
    void thread_input_1_V_data_10_V_read();
    void thread_input_1_V_data_11_V_read();
    void thread_input_1_V_data_12_V_read();
    void thread_input_1_V_data_13_V_read();
    void thread_input_1_V_data_14_V_read();
    void thread_input_1_V_data_15_V_read();
    void thread_input_1_V_data_16_V_read();
    void thread_input_1_V_data_17_V_read();
    void thread_input_1_V_data_18_V_read();
    void thread_input_1_V_data_19_V_read();
    void thread_input_1_V_data_1_V_read();
    void thread_input_1_V_data_20_V_read();
    void thread_input_1_V_data_21_V_read();
    void thread_input_1_V_data_22_V_read();
    void thread_input_1_V_data_23_V_read();
    void thread_input_1_V_data_24_V_read();
    void thread_input_1_V_data_25_V_read();
    void thread_input_1_V_data_26_V_read();
    void thread_input_1_V_data_27_V_read();
    void thread_input_1_V_data_28_V_read();
    void thread_input_1_V_data_29_V_read();
    void thread_input_1_V_data_2_V_read();
    void thread_input_1_V_data_30_V_read();
    void thread_input_1_V_data_31_V_read();
    void thread_input_1_V_data_3_V_read();
    void thread_input_1_V_data_4_V_read();
    void thread_input_1_V_data_5_V_read();
    void thread_input_1_V_data_6_V_read();
    void thread_input_1_V_data_7_V_read();
    void thread_input_1_V_data_8_V_read();
    void thread_input_1_V_data_9_V_read();
    void thread_layer2_out_V_data_V_din();
    void thread_layer2_out_V_data_V_write();
    void thread_myproject_Block_dot_product_array_array_ap_fixed_1u_config2_exit_proc_U0_ap_continue();
    void thread_myproject_Block_dot_product_array_array_ap_fixed_1u_config2_exit_proc_U0_ap_start();
    void thread_myproject_Block_dot_product_array_array_ap_fixed_1u_config2_exit_proc_U0_start_full_n();
    void thread_myproject_Block_dot_product_array_array_ap_fixed_1u_config2_exit_proc_U0_start_write();
    void thread_myproject_Block_preheader_i_i_033_proc45_U0_ap_continue();
    void thread_myproject_Block_preheader_i_i_033_proc45_U0_ap_start();
    void thread_myproject_Loop_1_proc_U0_ap_continue();
    void thread_myproject_Loop_1_proc_U0_ap_start();
    void thread_myproject_Loop_1_proc_U0_start_full_n();
    void thread_myproject_Loop_1_proc_U0_start_write();
    void thread_start_for_myproject_Loop_1_proc_U0_din();
};

}

using namespace ap_rtl;

#endif
